### ISSUE TITLE
 JSONDecodeError("Expecting value", s, err.value) from None 然后闪退

### ISSUE THREAD

**Issue by zjbbqlive** [SnapdragonLee/ChatGPT-weBot#21]
在前一个bug贴看到有大佬说过这个问题，没想到我也遇到了。之前的帖子信息太多，单独开了一个
部署一直能使用，中间调整过几次config，就关闭重启了几次main.py，突然就会提示以下信息后自动退出了，多次重试重启无效，重装WX和python也无法恢复。是最新的版本
`C:\Users\W10\Desktop\ChatGPT-weBot-master>python main.py
Traceback (most recent call last):
  File "C:\Users\W10\Desktop\ChatGPT-weBot-master\main.py", line 1, in <module>
    from client.wxclient import ws
  File "C:\Users\W10\Desktop\ChatGPT-weBot-master\client\wxclient.py", line 11, in <module>
    config = json.load(f)
             ^^^^^^^^^^^^
  File "C:\Users\W10\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\W10\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W10\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W10\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 16 (char 53)`

**Comment by SnapdragonLee** [comment]
注意你的文件编码问题，要存成utf-8

**Comment by zjbbqlive** [comment]
> 注意你的文件编码问题，要存成utf-8
只有config文件修改过,确认过,是UTF-8的,其他执行代码文件则是由您这边下载下来没修改过的

**Comment by zjbbqlive** [comment]
> 注意你的文件编码问题，要存成utf-8

谢谢大佬的提醒,我回头看了,默认配置文件存储格式是ANSI,这样反而是可以正常启动的.已经恢复,感谢

**Comment by SnapdragonLee** [comment]
> > 注意你的文件编码问题，要存成utf-8
> 
> 
> 
> 谢谢大佬的提醒,我回头看了,默认配置文件存储格式是ANSI,这样反而是可以正常启动的.已经恢复,感谢
啊这，好的 可以启动就好
